/*global module:false*/
module.exports = function(grunt) {

	// Project configuration.
	grunt.initConfig({
		
		pkg: {
			company: 'jamiecopeland',
			companyUrl: 'http://www.jamiecopeland.com',
			title: 'Project',
			version: '1.0.0'
		},
		
		meta: {
			banner: '/*! <%= pkg.title || pkg.name %> - v<%= pkg.version %> - ' +
			'<%= grunt.template.today("yyyy-mm-dd") %>\n' +
			'<%= pkg.homepage ? "* " + pkg.homepage + "\n" : "" %>' +
			'* Copyright (c) <%= grunt.template.today("yyyy") %> <%= pkg.author.name %>;' +
			' Licensed <%= _.pluck(pkg.licenses, "type").join(", ") %> */'
		},
		
		lint: {
			files: ['grunt.js', 'public/js/src/**/*.js']
		},

		jshint: {
			options: {
				curly: true,
				eqeqeq: false,
				immed: true,
				latedef: true,
				newcap: false,
				noarg: true,
				sub: true,
				boss: true,
				eqnull: true,
				browser: true,
				smarttabs: true
			},
			globals: {
				jQuery: true
			}
		},

		less: {
			desktop: {
				files: {
					'public/styles/main.css': 'public/styles/less/main.less'
				},
				options: {
					style: 'compact'
				}
			}
		},

		requirejs: {
			desktop: {
				options: {
					// For more information about these options see:
					// https://github.com/jrburke/r.js/blob/master/build/example.build.js
					baseUrl: 'public/js/src',
					mainConfigFile: 'public/js/src/boot.js',
					paths: {
						// Because lang is a url generated by the server we need to tell the
						// optimizer it doesn't exist as an actual file
						// 'lang': 'empty:'
					},
					name: 'boot',
					include: 'main',
					out: 'public/js/boot.min.js',
					optimize: 'uglify',
					uglify: {
						max_line_length: 32000
					}
				}
			}
		},

		watch: {
			// lint: {
			// 	files: '<config:lint.files>',
			// 	tasks: 'lint'
			// },
			less: {
				files: 'public/styles/less/**/*.less',
				tasks: 'less'
			}
		}
	});

	grunt.loadNpmTasks('grunt-contrib-less');
	grunt.loadNpmTasks('grunt-contrib-requirejs');

	// Default task.
	// grunt.registerTask('default', 'lint requirejs sass');
	grunt.registerTask('default', 'less');

};
